local game_state = require "common/game_state"
local moves = require "common/moves"

function init(self)
	msg.post(".", "acquire_input_focus")
	gui.set_enabled(gui.get_node("move_panel"), false)
end

function final(self)
end

function update(self, dt)

end

function on_message(self, message_id, message, sender)
	if message_id == hash("mon_selected") then
		
	elseif message_id == hash("move_selected") then
	
	end
end

function on_input(self, action_id, action)

end

function on_reload(self)
end
