function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	if(action_id == hash("touch") and action.released) then
		if(gui.pick_node(gui.get_node("exit_button"),action.x,action.y)) then
			msg.post("boss_select", "exit_button_pressed")
			return true
		end
	end
end

function on_reload(self)
end
